import type { Metadata } from "next";
import Link from "next/link";
import styles from "../page.module.css";

export const metadata: Metadata = {
  title: "Blog — Nutrição, Dietas e Receitas Saudáveis | Nutry.life",
  description: "Artigos sobre nutrição, dietas, jejum intermitente, low carb, vegano e muito mais. Conteúdo gratuito da equipe Nutry.life.",
  keywords: "blog nutrição, artigos dieta, jejum intermitente, low carb iniciantes, alimentação saudável",
  openGraph: {
    title: "Blog Nutry.life — Nutrição e Alimentação Saudável",
    description: "Artigos completos sobre nutrição, dietas e receitas saudáveis.",
    url: "https://nutry.life/blog",
  },
};

const posts = [
  {
    slug: "manteiga-vs-margarina-como-comparar",
    titulo: "Manteiga vs Margarina: Gorduras, Rótulo e Como Comparar",
    descricao: "Compare gorduras saturadas, gordura trans, sódio, ingredientes, porção e uso culinário sem depender de mitos.",
    data: "06 de agosto de 2026",
    tempo: "9 min de leitura",
    tag: "Escolhas Alimentares",
    emoji: "🧈",
  },
  {
    slug: "iogurte-natural-vs-grego-como-comparar",
    titulo: "Iogurte Natural vs Grego: Proteína, Açúcar e Como Comparar",
    descricao: "Compare proteína, açúcares adicionados, gordura, ingredientes, lactose e tamanho da porção antes de escolher.",
    data: "05 de agosto de 2026",
    tempo: "9 min de leitura",
    tag: "Escolhas Alimentares",
    emoji: "🥣",
  },
  {
    slug: "leite-de-vaca-vs-bebida-vegetal",
    titulo: "Leite de Vaca vs Bebida Vegetal: Como Comparar",
    descricao: "Compare proteínas, cálcio, vitamina D, açúcares e ingredientes de bebidas de soja, aveia, amêndoas, coco e leite.",
    data: "04 de agosto de 2026",
    tempo: "9 min de leitura",
    tag: "Escolhas Alimentares",
    emoji: "🥛",
  },
  {
    slug: "pao-integral-de-verdade-como-ler-rotulo",
    titulo: "Pão Integral de Verdade: Como Ler o Rótulo",
    descricao: "Veja os critérios da Anvisa e aprenda a comparar percentual integral, fibras, sódio e açúcares adicionados.",
    data: "03 de agosto de 2026",
    tempo: "8 min de leitura",
    tag: "Escolhas Alimentares",
    emoji: "🍞",
  },
  {
    slug: "acai-e-saudavel-polpa-pura-xarope",
    titulo: "Açaí é Saudável? Polpa Pura, Xarope e Como Escolher",
    descricao: "Entenda por que a composição do açaí varia tanto e como comparar ingredientes, açúcares adicionados e acompanhamentos.",
    data: "02 de agosto de 2026",
    tempo: "8 min de leitura",
    tag: "Alimentos",
    emoji: "🫐",
  },
  {
    slug: "creatina-para-mulheres-beneficios-retencao-seguranca",
    titulo: "Creatina para Mulheres: Benefícios, Retenção e Segurança",
    descricao: "Creatina causa inchaço? Entenda os benefícios para força e desempenho, os principais mitos e como avaliar o uso com segurança.",
    data: "01 de agosto de 2026",
    tempo: "9 min de leitura",
    tag: "Suplementação",
    emoji: "💪",
  },
  {
    slug: "whey-protein-vs-caseina-diferencas",
    titulo: "Whey Protein vs Caseína: Diferenças e Quando Usar",
    descricao: "Compare digestão, aminoácidos, saciedade e praticidade para entender quando whey ou caseína faz mais sentido.",
    data: "31 de julho de 2026",
    tempo: "8 min de leitura",
    tag: "Suplementação",
    emoji: "🥛",
  },
  {
    slug: "probioticos-cepas-que-funcionam",
    titulo: "Probióticos: Quais Cepas Funcionam e Para Que Servem?",
    descricao: "Entenda por que o efeito depende da cepa, da indicação e da dose estudada — e aprenda a ler o rótulo.",
    data: "30 de julho de 2026",
    tempo: "9 min de leitura",
    tag: "Saúde e Nutrição",
    emoji: "🦠",
  },
  {
    slug: "vitamina-b12-veganos-deficiencia-suplementacao",
    titulo: "Vitamina B12 para Veganos: Deficiência, Exames e Suplementação",
    descricao: "Por que dietas veganas exigem uma fonte confiável de B12, quais exames ajudam e quando buscar orientação.",
    data: "29 de julho de 2026",
    tempo: "8 min de leitura",
    tag: "Saúde e Nutrição",
    emoji: "🧬",
  },
  {
    slug: "melatonina-dose-quando-tomar-e-e-segura",
    titulo: "Melatonina: Dose Correta, Quando Tomar e Se É Segura Para Uso Diário",
    descricao: "Melatonina virou o suplemento para dormir mais popular. Mas a dose que a maioria usa é muito maior do que a necessária — e isso pode atrapalhar em vez de ajudar.",
    data: "28 de julho de 2026",
    tempo: "6 min de leitura",
    tag: "Suplementação",
    emoji: "💊",
  },
  {
    slug: "aveia-beneficios-tipos-e-como-consumir",
    titulo: "Aveia: Benefícios, Tipos e Como Consumir Para Aproveitar Ao Máximo",
    descricao: "Aveia é um dos alimentos funcionais mais estudados. Reduz colesterol, melhora saciedade e regula o intestino. Mas flocos, farinha ou farelo — qual forma funciona melhor?",
    data: "27 de julho de 2026",
    tempo: "6 min de leitura",
    tag: "Alimentação Prática",
    emoji: "🥗",
  },
  {
    slug: "indice-glicemico-o-que-e-e-importa-para-emagrecer",
    titulo: "Índice Glicêmico: O Que É e Realmente Importa Para Emagrecer?",
    descricao: "Índice glicêmico classifica alimentos pelo impacto na glicose sanguínea. Mas para emagrecer, ele importa tanto quanto o marketing promete?",
    data: "26 de julho de 2026",
    tempo: "6 min de leitura",
    tag: "Emagrecimento",
    emoji: "⚖️",
  },
  {
    slug: "colageno-hidrolisado-funciona-o-que-a-ciencia-diz",
    titulo: "Colágeno Hidrolisado Funciona? O Que a Ciência Realmente Diz",
    descricao: "Colágeno hidrolisado é um dos suplementos mais vendidos para pele, articulações e cabelo. Mas as evidências sustentam o hype? A resposta é mais nuançada do que sim ou não.",
    data: "25 de julho de 2026",
    tempo: "6 min de leitura",
    tag: "Suplementação",
    emoji: "💊",
  },
  {
    slug: "ferritina-baixa-sintomas-e-o-que-comer",
    titulo: "Ferritina Baixa: Sintomas, Causas e O Que Comer Para Recuperar",
    descricao: "Ferritina baixa é o estágio anterior à anemia — e muita gente tem sem saber. Cansaço, queda de cabelo e falta de ar podem ser sinais. Saiba como identificar e o que fazer.",
    data: "24 de julho de 2026",
    tempo: "6 min de leitura",
    tag: "Saúde e Nutrição",
    emoji: "🧬",
  },
  {
    slug: "cacau-vs-chocolate-qual-e-mais-saudavel",
    titulo: "Cacau vs Chocolate: Qual é Mais Saudável e Vale Comer Todo Dia?",
    descricao: "Cacau puro é antioxidante, anti-inflamatório e até cardioprotegido. Mas o chocolate que compramos tem pouco cacau de verdade. Entenda o que vale comer e em qual quantidade.",
    data: "23 de julho de 2026",
    tempo: "6 min de leitura",
    tag: "Saúde e Nutrição",
    emoji: "🧬",
  },
  {
    slug: "potassio-para-que-serve-e-onde-encontrar",
    titulo: "Potássio: Para Que Serve, Sintomas de Deficiência e Onde Encontrar",
    descricao: "Potássio regula pressão arterial, função muscular e saúde do coração. E a maioria das pessoas consome menos do que precisa — sem saber.",
    data: "22 de julho de 2026",
    tempo: "6 min de leitura",
    tag: "Saúde e Nutrição",
    emoji: "🧬",
  },
  {
    slug: "hidratacao-quantos-litros-de-agua-por-dia",
    titulo: "Hidratação: Os 2 Litros de Água Por Dia São Obrigatórios?",
    descricao: "2 litros de água por dia é um dos conselhos mais repetidos. Mas de onde veio esse número? É o mesmo para todo mundo? E café e chá contam?",
    data: "21 de julho de 2026",
    tempo: "6 min de leitura",
    tag: "Saúde e Nutrição",
    emoji: "🧬",
  },
  {
    slug: "proteina-vegetal-completa-como-combinar",
    titulo: "Proteína Vegetal Completa: Como Combinar Alimentos Para Não Faltar Aminoácido",
    descricao: "Proteínas vegetais são geralmente incompletas — faltam um ou mais aminoácidos essenciais. Mas com as combinações certas, é possível ter proteína completa sem nenhum alimento animal.",
    data: "20 de julho de 2026",
    tempo: "6 min de leitura",
    tag: "Alimentação Prática",
    emoji: "🥗",
  },
  {
    slug: "comer-de-3-em-3-horas-e-necessario",
    titulo: "Comer de 3 em 3 Horas é Necessário? O Mito do Metabolismo",
    descricao: "Comer de 3 em 3 horas para 'acelerar o metabolismo' foi um dos conselhos mais repetidos da nutrição. Mas a ciência revisou essa ideia — e a conclusão surpreende.",
    data: "19 de julho de 2026",
    tempo: "6 min de leitura",
    tag: "Emagrecimento",
    emoji: "⚖️",
  },
  {
    slug: "inulina-e-prebiotico-o-que-e-e-para-que-serve",
    titulo: "Inulina e Prebióticos: O Que São e Por Que Importam Para Sua Saúde?",
    descricao: "Prebióticos são o alimento das bactérias boas do intestino. Sem eles, até o melhor probiótico perde eficiência. Entenda o que são, onde encontrar e quando suplementar.",
    data: "18 de julho de 2026",
    tempo: "6 min de leitura",
    tag: "Saúde e Nutrição",
    emoji: "🧬",
  },
  {
    slug: "como-aumentar-testosterona-naturalmente",
    titulo: "Como Aumentar Testosterona Naturalmente: O Que Funciona de Verdade?",
    descricao: "Testosterona baixa afeta humor, disposição, libido e massa muscular. Mas o que realmente funciona para aumentá-la naturalmente — sem suplementos caros ou hormônios?",
    data: "17 de julho de 2026",
    tempo: "6 min de leitura",
    tag: "Saúde e Nutrição",
    emoji: "🧬",
  },
  {
    slug: "sal-de-erva-doce-vs-sal-rosa-himalaia-vale-a-pena",
    titulo: "Sal Rosa do Himalaia Vale Mais que Sal Comum? A Verdade",
    descricao: "Sal rosa do Himalaia é vendido como mais saudável e cheio de minerais. Mas a ciência sustenta essas afirmações? Comparação honesta com o sal comum.",
    data: "16 de julho de 2026",
    tempo: "6 min de leitura",
    tag: "Saúde e Nutrição",
    emoji: "🧬",
  },
  {
    slug: "albumina-vale-a-pena-como-suplemento",
    titulo: "Albumina Vale a Pena Como Suplemento? Comparação com Whey",
    descricao: "Albumina é proteína de clara de ovo e custa menos que o whey. Mas ela entrega o mesmo resultado? Comparação honesta de absorção, aminoácidos e custo-benefício.",
    data: "15 de julho de 2026",
    tempo: "6 min de leitura",
    tag: "Suplementação",
    emoji: "💊",
  },
  {
    slug: "vitamina-d-sol-suplemento-ou-alimento",
    titulo: "Vitamina D: Sol, Suplemento ou Alimento — O Que Funciona Melhor?",
    descricao: "Vitamina D é deficiente em mais de 70% dos brasileiros apesar de morarmos em país tropical. Por que isso acontece e como corrigir de forma eficiente?",
    data: "14 de julho de 2026",
    tempo: "6 min de leitura",
    tag: "Saúde e Nutrição",
    emoji: "🧬",
  },
  {
    slug: "fibra-alimentar-para-que-serve",
    titulo: "Fibra Alimentar: Para Que Serve e Por Que a Maioria Come Pouco?",
    descricao: "Fibra alimentar regula o intestino, controla o colesterol e melhora a saciedade. Mas o brasileiro consome em média metade do recomendado. Saiba como corrigir isso.",
    data: "13 de julho de 2026",
    tempo: "6 min de leitura",
    tag: "Saúde e Nutrição",
    emoji: "🧬",
  },
  {
    slug: "carboidrato-a-noite-engorda",
    titulo: "Carboidrato à Noite Engorda? O Que a Ciência Diz",
    descricao: "Cortar carboidrato à noite é um dos conselhos mais populares para emagrecer. Mas quando os estudos testam isso de forma controlada, o resultado surpreende.",
    data: "12 de julho de 2026",
    tempo: "5 min de leitura",
    tag: "Emagrecimento",
    emoji: "⚖️",
  },
  {
    slug: "vitamina-c-dose-suplemento-ou-fruta",
    titulo: "Vitamina C: Dose Diária, Suplemento ou Fruta Resolve?",
    descricao: "Vitamina C virou sinônimo de imunidade — mas megadoses resolvem gripas? E a famosa laranja dá conta sozinha? O que a ciência realmente mostra.",
    data: "11 de julho de 2026",
    tempo: "5 min de leitura",
    tag: "Saúde e Nutrição",
    emoji: "🧬",
  },
  {
    slug: "proteina-carne-vs-frango-qual-mais-completa",
    titulo: "Proteína da Carne vs Frango: Qual é Mais Completa?",
    descricao: "Frango lidera a marmita fit. Mas a carne vermelha tem nutrientes que o frango não entrega. Qual realmente é mais completa para quem treina?",
    data: "10 de julho de 2026",
    tempo: "5 min de leitura",
    tag: "Alimentação Prática",
    emoji: "🥗",
  },
  {
    slug: "omega-3-para-que-serve",
    titulo: "Ômega-3: Para Que Serve, Qual Dose e Qual Marca Comprar",
    descricao: "Ômega-3 é um dos suplementos mais estudados do mundo — com benefícios reais para coração, cérebro e inflamação. Mas a dose e a qualidade importam muito mais do que a maioria imagina.",
    data: "09 de julho de 2026",
    tempo: "6 min de leitura",
    tag: "Suplementação",
    emoji: "💊",
  },
  {
    slug: "magnesio-para-que-serve",
    titulo: "Magnésio: Para Que Serve, Quem Precisa e Qual Tipo Comprar",
    descricao: "O magnésio participa de mais de 300 reações enzimáticas no corpo. Estudos mostram que mais de 70% dos brasileiros não consomem o suficiente. Saiba o que isso significa na prática.",
    data: "08 de julho de 2026",
    tempo: "6 min de leitura",
    tag: "Saúde e Nutrição",
    emoji: "🧬",
  },
  {
    slug: "bcaa-vale-a-pena-ou-e-dinheiro-jogado-fora",
    titulo: "BCAA Vale a Pena ou É Dinheiro Jogado Fora?",
    descricao: "BCAA foi o suplemento mais vendido por décadas. Mas com o que sabemos hoje sobre proteína e síntese muscular, ainda faz sentido comprar? A resposta pode te surpreender.",
    data: "07 de julho de 2026",
    tempo: "6 min de leitura",
    tag: "Suplementação",
    emoji: "💊",
  },
  {
    slug: "proteina-no-cafe-da-manha-importa",
    titulo: "Proteína no Café da Manhã: Realmente Faz Diferença?",
    descricao: "Incluir proteína no café da manhã está em alta — promete saciedade, perda de peso e mais energia. Mas a ciência sustenta essa recomendação?",
    data: "06 de julho de 2026",
    tempo: "6 min de leitura",
    tag: "Alimentação Prática",
    emoji: "🥗",
  },
  {
    slug: "pre-treino-vale-a-pena-ou-e-perigoso",
    titulo: "Pré-Treino Vale a Pena ou É Perigoso? Guia Honesto",
    descricao: "Pré-treino promete mais energia, foco e performance. Mas formulas com doses altas de cafeína e outros estimulantes preocupam. Vale o risco?",
    data: "05 de julho de 2026",
    tempo: "6 min de leitura",
    tag: "Suplementação",
    emoji: "💊",
  },
  {
    slug: "ovos-todos-os-dias-faz-mal",
    titulo: "Comer Ovos Todo Dia Faz Mal? O Que a Ciência Diz em 2026",
    descricao: "Durante décadas, o ovo foi vilão da dieta por causa do colesterol. Mas a ciência revisou essa posição. Quantos ovos por dia são seguros e para quem?",
    data: "04 de julho de 2026",
    tempo: "6 min de leitura",
    tag: "Saúde e Nutrição",
    emoji: "🧬",
  },
  {
    slug: "jejum-intermitente-vs-restricao-calorica",
    titulo: "Jejum Intermitente vs Restrição Calórica: O Que Funciona Melhor?",
    descricao: "Jejum intermitente promete resultados além do emagrecimento: autofagia, longevidade, saúde metabólica. Mas comparado à restrição calórica tradicional, o que as pesquisas mostram?",
    data: "03 de julho de 2026",
    tempo: "6 min de leitura",
    tag: "Emagrecimento",
    emoji: "⚖️",
  },
  {
    slug: "whey-concentrado-vs-isolado",
    titulo: "Whey Concentrado vs Isolado: Qual Vale Mais a Pena?",
    descricao: "Whey isolado custa até o dobro do concentrado. Mas essa diferença de preço se justifica em ganho muscular real? A resposta depende do seu perfil.",
    data: "02 de julho de 2026",
    tempo: "6 min de leitura",
    tag: "Suplementação",
    emoji: "💊",
  },
  {
    slug: "dieta-low-carb-vs-dieta-equilibrada",
    titulo: "Dieta Low Carb vs Dieta Equilibrada: Qual Emagrece Mais?",
    descricao: "Low carb virou moda e promete resultados rápidos. Mas a dieta equilibrada com déficit calórico entrega menos? O que as pesquisas mostram quando comparam as duas.",
    data: "01 de julho de 2026",
    tempo: "6 min de leitura",
    tag: "Emagrecimento",
    emoji: "⚖️",
  },
  {
    slug: "acucar-vs-adocante-qual-e-pior",
    titulo: "Açúcar vs Adoçante: Qual é Pior Para a Saúde?",
    descricao: "Trocar açúcar por adoçante parece a escolha óbvia para quem quer emagrecer. Mas a ciência tem respostas mais complexas sobre qual realmente prejudica mais.",
    data: "30 de junho de 2026",
    tempo: "6 min de leitura",
    tag: "Saúde e Nutrição",
    emoji: "🧬",
  },
  {
    slug: "creatina-monohidratada-vs-creapure",
    titulo: "Creatina Monohidratada vs Creapure: Vale Pagar Mais Caro?",
    descricao: "Creapure é apresentada como a creatina mais pura do mercado. Mas a creatina monohidratada comum entrega o mesmo resultado? A resposta vai te surpreender.",
    data: "29 de junho de 2026",
    tempo: "6 min de leitura",
    tag: "Suplementação",
    emoji: "💊",
  },
  {
    slug: "glutamina-vale-a-pena",
    titulo: "Glutamina Vale a Pena? O Que a Ciência Realmente Diz",
    descricao: "Glutamina é um dos suplementos mais vendidos nas academias. Mas os estudos mostram que para a maioria das pessoas, ela não faz o que promete. Entenda quando ela de fato ajuda.",
    data: "28 de junho de 2026",
    tempo: "5 min de leitura",
    tag: "Suplementação",
    emoji: "💊",
  },
  {
    slug: "deficit-calorico-como-calcular",
    titulo: "Déficit Calórico: Como Calcular o Seu e Emagrecer Sem Passar Fome",
    descricao: "Todo emagrecimento depende de um déficit calórico. Mas quanto déficit é seguro? E como fazer isso sem passar fome ou perder músculo?",
    data: "27 de junho de 2026",
    tempo: "7 min de leitura",
    tag: "Emagrecimento",
    emoji: "⚖️",
  },
  {
    slug: "como-montar-marmita-saudavel",
    titulo: "Como Montar uma Marmita Saudável e Barata Para o Trabalho",
    descricao: "Comer bem no trabalho não precisa ser complicado nem caro. Com uma estrutura simples e um pouco de organização, você come melhor gastando menos do que no restaurante.",
    data: "26 de junho de 2026",
    tempo: "5 min de leitura",
    tag: "Alimentação Prática",
    emoji: "🥗",
  },
  {
    slug: "colesterol-alto-o-que-comer",
    titulo: "Colesterol Alto: O Que Comer e Evitar Para Controlar",
    descricao: "Colesterol alto não é sentença de cortar toda gordura. A ciência atual mostra que o problema é mais específico — e a solução também.",
    data: "25 de junho de 2026",
    tempo: "6 min de leitura",
    tag: "Saúde e Nutrição",
    emoji: "🧬",
  },
  {
    slug: "creatina-para-que-serve",
    titulo: "Creatina: Para Que Serve, Quem Pode Tomar e Como Usar",
    descricao: "A creatina é o suplemento mais estudado da ciência do esporte — e também um dos mais mal compreendidos. Saiba o que ela faz de verdade, quem se beneficia e como usar corretamente.",
    data: "24 de junho de 2026",
    tempo: "6 min de leitura",
    tag: "Suplementação",
    emoji: "💊",
  },
  {
    slug: "whey-protein-vs-proteina-vegetal",
    titulo: "Whey Protein vs Proteína Vegetal: Qual Vale Mais a Pena em 2026?",
    descricao: "Whey é mais completo e absorvido mais rápido. Proteína vegetal é mais acessível e funciona para veganos e intolerantes à lactose. Mas qual realmente faz diferença no resultado?",
    data: "23 de junho de 2026",
    tempo: "6 min de leitura",
    tag: "Suplementação",
    emoji: "💊",
  },
  {
    slug: "como-organizar-feira-semanal",
    titulo: "Como Organizar a Feira Semanal de Forma Saudável e Sem Desperdício",
    descricao: "Como Organizar a Feira Semanal de Forma Saudável e Sem Desperdício",
    data: "22 de junho de 2026",
    tempo: "6 min de leitura",
    tag: "Planejamento",
    emoji: "🛒",
  },
  {
    slug: "zinco-na-alimentacao",
    titulo: "Zinco na Alimentação: Para Que Serve e Quais Alimentos São Boas Fontes",
    descricao: "Zinco na Alimentação: Para Que Serve e Quais Alimentos São Boas Fontes",
    data: "21 de junho de 2026",
    tempo: "6 min de leitura",
    tag: "Nutrição",
    emoji: "🦪",
  },
  {
    slug: "dieta-cetogenica-funciona",
    titulo: "Dieta Cetogênica Funciona Mesmo? O Que a Ciência Diz",
    descricao: "Dieta Cetogênica Funciona Mesmo? O Que a Ciência Diz",
    data: "20 de junho de 2026",
    tempo: "7 min de leitura",
    tag: "Dietas",
    emoji: "🥑",
  },
  {
    slug: "alimentos-ricos-em-ferro",
    titulo: "Alimentos Ricos em Ferro: Quais Funcionam de Verdade",
    descricao: "Alimentos Ricos em Ferro: Quais Funcionam de Verdade",
    data: "19 de junho de 2026",
    tempo: "6 min de leitura",
    tag: "Nutrição",
    emoji: "🥩",
  },
  {
    slug: "intolerancia-a-lactose-alimentacao",
    titulo: "Intolerância à Lactose: O Que Comer e Como Não Perder Nutrientes",
    descricao: "Intolerância à Lactose: O Que Comer e Como Não Perder Nutrientes",
    data: "18 de junho de 2026",
    tempo: "6 min de leitura",
    tag: "Saúde",
    emoji: "🥛",
  },
  {
    slug: "dieta-mediterranea-guia",
    titulo: "Dieta Mediterrânea: Guia Completo Para Começar Sem Complicação",
    descricao: "Dieta Mediterrânea: Guia Completo Para Começar Sem Complicação",
    data: "17 de junho de 2026",
    tempo: "7 min de leitura",
    tag: "Dietas",
    emoji: "🫒",
  },
  {
    slug: "omega-3-beneficios-e-fontes",
    titulo: "Ômega-3: Benefícios Reais e as Melhores Fontes Além do Peixe",
    descricao: "Ômega-3: Benefícios Reais e as Melhores Fontes Além do Peixe",
    data: "16 de junho de 2026",
    tempo: "7 min de leitura",
    tag: "Nutrição",
    emoji: "🐟",
  },
  {
    slug: "vitaminas-para-imunidade",
    titulo: "Vitaminas Para Imunidade: O Que Realmente Funciona",
    descricao: "Vitaminas Para Imunidade: O Que Realmente Funciona",
    data: "15 de junho de 2026",
    tempo: "7 min de leitura",
    tag: "Nutrição",
    emoji: "🛡️",
  },
  {
    slug: "o-que-comer-no-cafe-da-manha-para-emagrecer",
    titulo: "O Que Comer no Café da Manhã Para Emagrecer",
    descricao: "O Que Comer no Café da Manhã Para Emagrecer",
    data: "14 de junho de 2026",
    tempo: "7 min de leitura",
    tag: "Nutrição",
    emoji: "🌅",
  },
  {
    slug: "alimentos-que-dao-saciedade",
    titulo: "Alimentos Que Dão Mais Saciedade: Como Comer Menos Sem Passar Fome",
    descricao: "Alimentos Que Dão Mais Saciedade: Como Comer Menos Sem Passar Fome",
    data: "13 de junho de 2026",
    tempo: "7 min de leitura",
    tag: "Nutrição",
    emoji: "🥗",
  },
  {
    slug: "como-ganhar-massa-sem-suplemento",
    titulo: "Como Ganhar Massa Muscular Sem Suplemento",
    descricao: "Como Ganhar Massa Muscular Sem Suplemento",
    data: "12 de junho de 2026",
    tempo: "7 min de leitura",
    tag: "Nutrição",
    emoji: "💪",
  },
  {
    slug: "diabetes-tipo-2-alimentacao",
    titulo: "Alimentação Para Diabetes Tipo 2: Controle a Glicose Pelo Prato",
    descricao: "Alimentação Para Diabetes Tipo 2: Controle a Glicose Pelo Prato",
    data: "11 de junho de 2026",
    tempo: "7 min de leitura",
    tag: "Nutrição",
    emoji: "🩺",
  },
  {
    slug: "proteina-para-vegetarianos",
    titulo: "Proteína Para Vegetarianos: As Melhores Fontes",
    descricao: "Proteína Para Vegetarianos: As Melhores Fontes",
    data: "10 de junho de 2026",
    tempo: "7 min de leitura",
    tag: "Nutrição",
    emoji: "🌱",
  },
  {
    slug: "como-comer-bem-com-pouco-dinheiro",
    titulo: "Como Comer Bem Com Pouco Dinheiro",
    descricao: "Como Comer Bem Com Pouco Dinheiro",
    data: "9 de junho de 2026",
    tempo: "7 min de leitura",
    tag: "Nutrição",
    emoji: "💰",
  },
  {
    slug: "alimentacao-anti-envelhecimento",
    titulo: "Alimentação Anti-Envelhecimento: Nutrientes Que Protegem Suas Células",
    descricao: "Alimentação Anti-Envelhecimento: Nutrientes Que Protegem Suas Células",
    data: "8 de junho de 2026",
    tempo: "7 min de leitura",
    tag: "Nutrição",
    emoji: "⏳",
  },
  {
    slug: "como-perder-gordura-abdominal",
    titulo: "Como Perder Gordura Abdominal: O Que a Ciência Diz",
    descricao: "Como Perder Gordura Abdominal: O Que a Ciência Diz",
    data: "7 de junho de 2026",
    tempo: "7 min de leitura",
    tag: "Nutrição",
    emoji: "🎯",
  },
  {
    slug: "dieta-vegetariana-proteina",
    titulo: "Dieta Vegetariana: Como Garantir Proteína Suficiente",
    descricao: "Dieta Vegetariana: Como Garantir Proteína Suficiente",
    data: "6 de junho de 2026",
    tempo: "7 min de leitura",
    tag: "Nutrição",
    emoji: "🥦",
  },
  {
    slug: "alimentacao-pre-treino",
    titulo: "Alimentação Pré-Treino: O Que Comer Para Mais Energia",
    descricao: "Alimentação Pré-Treino: O Que Comer Para Mais Energia",
    data: "5 de junho de 2026",
    tempo: "7 min de leitura",
    tag: "Nutrição",
    emoji: "💪",
  },
  {
    slug: "como-ler-rotulo-de-alimentos",
    titulo: "Como Ler Rótulo de Alimentos: O Guia Definitivo",
    descricao: "Como Ler Rótulo de Alimentos: O Guia Definitivo",
    data: "4 de junho de 2026",
    tempo: "7 min de leitura",
    tag: "Nutrição",
    emoji: "🏷️",
  },
  {
    slug: "dieta-para-tireoide",
    titulo: "Dieta Para Tireoide: O Que Comer e Evitar",
    descricao: "Dieta Para Tireoide: O Que Comer e Evitar",
    data: "3 de junho de 2026",
    tempo: "7 min de leitura",
    tag: "Nutrição",
    emoji: "🦋",
  },
  {
    slug: "planejamento-alimentar-semanal",
    titulo: "Planejamento Alimentar Semanal: Como Planejar Refeições e Poupar Tempo",
    descricao: "Planejar as refeições da semana economiza tempo, reduz desperdício e facilita manter uma alimentação saudável.",
    data: "2 de junho de 2026",
    tempo: "7 min de leitura",
    tag: "Organização",
    emoji: "📋",
  },
  {
    slug: "carboidratos-bons-e-ruins",
    titulo: "Carboidratos Bons e Ruins: Guia Para Não Ter Medo de Carbs",
    descricao: "Aprenda a diferença entre carboidratos simples e complexos, índice glicêmico e como incluir carbs de forma inteligente.",
    data: "1 de junho de 2026",
    tempo: "7 min de leitura",
    tag: "Carboidratos",
    emoji: "🌾",
  },
  {
    slug: "magnesio-na-alimentacao",
    titulo: "Magnésio: Por Que Você Provavelmente Está com Deficiência",
    descricao: "Câimbras, insônia, ansiedade, fadiga — muitos desses sintomas são de deficiência de magnésio.",
    data: "31 de maio de 2026",
    tempo: "7 min de leitura",
    tag: "Minerais",
    emoji: "💊",
  },
  {
    slug: "jejum-intermitente-24-horas",
    titulo: "Jejum de 24 Horas: Como Fazer, Benefícios e Quem Deve Evitar",
    descricao: "O jejum de 24h tem benefícios potentes mas exige preparo. Veja como fazer corretamente e quem não deve tentar.",
    data: "30 de maio de 2026",
    tempo: "7 min de leitura",
    tag: "Jejum Intermitente",
    emoji: "⏱️",
  },
  {
    slug: "alimentos-anti-inflamatorios",
    titulo: "Alimentos Anti-inflamatórios: Lista Completa e Como Usar",
    descricao: "A inflamação crônica está por trás de diabetes, doenças cardíacas e obesidade. Veja a lista completa de alimentos que combatem a inflamação.",
    data: "29 de maio de 2026",
    tempo: "7 min de leitura",
    tag: "Anti-inflamatório",
    emoji: "🫚",
  },
  {
    slug: "como-montar-prato-equilibrado",
    titulo: "Como Montar um Prato Equilibrado Pelo Método do Prato",
    descricao: "O método do prato divide a refeição em proporções simples sem precisar contar calorias.",
    data: "28 de maio de 2026",
    tempo: "7 min de leitura",
    tag: "Nutrição",
    emoji: "🍽️",
  },
  {
    slug: "vitamina-d-deficiencia",
    titulo: "Vitamina D: Por Que Quase Todo Brasileiro Tem Deficiência",
    descricao: "Mais de 77% dos brasileiros têm deficiência de vitamina D. Veja sintomas, fontes alimentares e quando suplementar.",
    data: "27 de maio de 2026",
    tempo: "7 min de leitura",
    tag: "Vitaminas",
    emoji: "☀️",
  },
  {
    slug: "como-comer-fora-e-manter-dieta",
    titulo: "Como Comer Fora de Casa e Manter a Dieta",
    descricao: "Restaurante, lanchonete, happy hour: manter a dieta fora de casa tem estratégias simples e eficazes.",
    data: "26 de maio de 2026",
    tempo: "7 min de leitura",
    tag: "Alimentação Saudável",
    emoji: "🍴",
  },
  {
    slug: "colageno-na-alimentacao",
    titulo: "Colágeno na Alimentação: O Que Realmente Funciona Para a Pele",
    descricao: "Suplementar colágeno ou comer os alimentos certos? Veja o que a ciência diz sobre colágeno na dieta.",
    data: "25 de maio de 2026",
    tempo: "7 min de leitura",
    tag: "Pele e Nutrição",
    emoji: "✨",
  },
  {
    slug: "dieta-para-hipertensao",
    titulo: "Dieta para Hipertensão: O Que Comer e O Que Evitar",
    descricao: "Pressão alta afeta 36% dos brasileiros. Veja a dieta DASH, alimentos que reduzem a pressão e os que devem ser evitados.",
    data: "24 de maio de 2026",
    tempo: "7 min de leitura",
    tag: "Saúde",
    emoji: "❤️",
  },
  {
    slug: "prebioticos-e-probioticos",
    titulo: "Prebióticos e Probióticos: Diferença, Benefícios e Onde Encontrar",
    descricao: "Seu intestino contém mais neurônios que sua medula espinhal. Entenda como prebióticos e probióticos cuidam do seu microbioma.",
    data: "23 de maio de 2026",
    tempo: "7 min de leitura",
    tag: "Saúde Intestinal",
    emoji: "🦠",
  },
  {
    slug: "como-reduzir-o-acucar-da-dieta",
    titulo: "Como Reduzir o Açúcar da Dieta Sem Sofrimento",
    descricao: "O açúcar adicionado está em tudo. Veja como identificá-lo nos rótulos, substituições práticas e como reduzir sem abrir mão do sabor.",
    data: "22 de maio de 2026",
    tempo: "7 min de leitura",
    tag: "Alimentação Saudável",
    emoji: "🍬",
  },
  {
    slug: "gorduras-boas-e-ruins",
    titulo: "Gorduras Boas e Ruins: Qual a Diferença e Quais Comer",
    descricao: "Nem toda gordura engorda. Aprenda a diferença entre gorduras boas (insaturadas) e ruins (trans e saturadas).",
    data: "21 de maio de 2026",
    tempo: "7 min de leitura",
    tag: "Nutrição",
    emoji: "🥑",
  },
  {
    slug: "hidratacao-e-saude",
    titulo: "Hidratação e Saúde: Quanto Água Beber Por Dia de Verdade",
    descricao: "Beber 2 litros por dia é genérico. Veja como calcular sua necessidade real e por que a hidratação impacta o emagrecimento.",
    data: "20 de maio de 2026",
    tempo: "7 min de leitura",
    tag: "Nutrição",
    emoji: "💧",
  },
  {
    slug: "alimentos-ricos-em-fibras",
    titulo: "Alimentos ricos em fibras: lista completa e benefícios",
    descricao: "Ranking dos alimentos com mais fibra por 100g, diferença entre fibra solúvel e insolúvel e como atingir sua meta diária de 25–30g.",
    data: "19 de maio de 2026",
    tempo: "8 min de leitura",
    tag: "Nutrição",
    emoji: "🌾",
  },
  {
    slug: "como-acelerar-o-metabolismo",
    titulo: "Como acelerar o metabolismo: 10 estratégias que funcionam de verdade",
    descricao: "10 estratégias comprovadas para acelerar o metabolismo naturalmente — com o impacto calórico estimado de cada uma. Sem suplementos caros.",
    data: "18 de maio de 2026",
    tempo: "9 min de leitura",
    tag: "Metabolismo",
    emoji: "🔥",
  },
  {
    slug: "cafe-da-manha-saudavel",
    titulo: "Café da manhã saudável: 10 opções rápidas e nutritivas",
    descricao: "10 opções de café da manhã saudável com tempo de preparo, calorias, proteínas e dicas práticas para cada uma.",
    data: "17 de maio de 2026",
    tempo: "8 min de leitura",
    tag: "Alimentação Saudável",
    emoji: "☀️",
  },
  {
    slug: "alimentacao-para-ansiedade",
    titulo: "Alimentação para ansiedade: o que comer para acalmar",
    descricao: "Como o eixo intestino-cérebro funciona, os nutrientes que reduzem a ansiedade e o que evitar para não piorar os sintomas.",
    data: "16 de maio de 2026",
    tempo: "9 min de leitura",
    tag: "Saúde Mental & Nutrição",
    emoji: "🧠",
  },
  {
    slug: "como-ganhar-massa-muscular-sendo-magro",
    titulo: "Como ganhar massa muscular sendo magro: guia completo",
    descricao: "Por que ectomorfos têm dificuldade de ganhar massa, quantas calorias comer, melhores alimentos hipercalóricos e cardápio de 3.200 kcal de exemplo.",
    data: "14 de maio de 2026",
    tempo: "9 min de leitura",
    tag: "Hipertrofia",
    emoji: "🦴",
  },
  {
    slug: "dieta-low-carb",
    titulo: "Dieta low carb: o que é, como funciona e cardápio completo",
    descricao: "Guia completo de low carb: níveis de restrição, como o corpo muda, benefícios, alimentos permitidos, cardápio de exemplo e como evitar a gripe low carb.",
    data: "13 de maio de 2026",
    tempo: "10 min de leitura",
    tag: "Low Carb",
    emoji: "🥑",
  },
  {
    slug: "alimentos-que-fortalecem-o-sistema-imunologico",
    titulo: "Alimentos que fortalecem o sistema imunológico: lista completa",
    descricao: "15 alimentos que aumentam a imunidade com o mecanismo científico de cada um, o que evitar e cardápio de 1 dia focado em imunidade.",
    data: "12 de maio de 2026",
    tempo: "9 min de leitura",
    tag: "Imunidade",
    emoji: "🛡️",
  },
  {
    slug: "vitaminas-e-minerais-essenciais",
    titulo: "Vitaminas e minerais essenciais: para que serve cada um",
    descricao: "Guia completo com funções, sintomas de deficiência e fontes alimentares de todas as vitaminas e minerais — incluindo os 4 mais deficientes no Brasil.",
    data: "11 de maio de 2026",
    tempo: "10 min de leitura",
    tag: "Nutrição",
    emoji: "💊",
  },
  {
    slug: "como-perder-peso-sem-fazer-dieta",
    titulo: "Como perder peso sem fazer dieta: 10 mudanças que funcionam",
    descricao: "10 hábitos simples e sustentáveis que criam déficit calórico sem restrições radicais — com o impacto em kcal estimado para cada mudança.",
    data: "10 de maio de 2026",
    tempo: "9 min de leitura",
    tag: "Emagrecimento",
    emoji: "🏃",
  },
  {
    slug: "alimentos-que-ajudam-a-dormir",
    titulo: "Alimentos que ajudam a dormir melhor: lista completa",
    descricao: "12 alimentos que melhoram o sono, o que evitar antes de dormir, o papel do triptofano e 3 opções de jantar para uma noite tranquila.",
    data: "9 de maio de 2026",
    tempo: "8 min de leitura",
    tag: "Sono & Saúde",
    emoji: "😴",
  },
  {
    slug: "dieta-para-diabeticos",
    titulo: "Dieta para diabéticos: o que comer e o que evitar",
    descricao: "Guia completo de alimentação para diabetes tipo 2: alimentos permitidos, proibidos, estratégias para controle glicêmico e cardápio de exemplo.",
    data: "8 de maio de 2026",
    tempo: "10 min de leitura",
    tag: "Saúde Metabólica",
    emoji: "🩸",
  },
  {
    slug: "o-que-comer-para-ter-mais-energia",
    titulo: "O que comer para ter mais energia no dia a dia",
    descricao: "Os 12 alimentos que aumentam energia de verdade, o que evitar e como manter glicose estável do café da manhã ao jantar.",
    data: "7 de maio de 2026",
    tempo: "8 min de leitura",
    tag: "Nutrição",
    emoji: "⚡",
  },
  {
    slug: "como-diminuir-o-colesterol",
    titulo: "Como diminuir o colesterol com alimentação: guia completo",
    descricao: "O que é LDL, HDL e triglicerídeos, quais alimentos pioram e quais melhoram o perfil lipídico, e um cardápio anti-colesterol de exemplo.",
    data: "6 de maio de 2026",
    tempo: "9 min de leitura",
    tag: "Saúde Metabólica",
    emoji: "❤️",
  },
  {
    slug: "alimentos-ricos-em-proteina",
    titulo: "Alimentos ricos em proteína: lista completa com quantidade",
    descricao: "Ranking completo dos alimentos com mais proteína por 100g — animais e vegetais — com dicas de uso e como bater sua meta diária.",
    data: "5 de maio de 2026",
    tempo: "8 min de leitura",
    tag: "Nutrição",
    emoji: "🥩",
  },
  {
    slug: "dieta-para-ganhar-massa-muscular",
    titulo: "Dieta para ganhar massa muscular: o que comer e como montar",
    descricao: "Calorias, proteína, macros e cardápio completo para hipertrofia. O guia definitivo de nutrição para quem quer ganhar massa de verdade.",
    data: "4 de maio de 2026",
    tempo: "10 min de leitura",
    tag: "Hipertrofia",
    emoji: "💪",
  },
  {
    slug: "como-perder-barriga",
    titulo: "Como perder barriga: o que funciona de verdade (e o que não funciona)",
    descricao: "A ciência da gordura abdominal, os mitos que não funcionam e as 6 estratégias comprovadas para eliminar a barriga de forma duradoura.",
    data: "3 de maio de 2026",
    tempo: "10 min de leitura",
    tag: "Emagrecimento",
    emoji: "🎯",
  },
  {
    slug: "o-que-comer-antes-e-depois-do-treino",
    titulo: "O que comer antes e depois do treino: guia completo",
    descricao: "Timing ideal, melhores alimentos, combinações prontas e dicas para quem treina em jejum. Tudo que você precisa saber sobre nutrição peri-treino.",
    data: "2 de maio de 2026",
    tempo: "9 min de leitura",
    tag: "Treino & Nutrição",
    emoji: "💪",
  },
  {
    slug: "alimentos-que-inflamam-o-corpo",
    titulo: "Alimentos que inflamam o corpo: lista completa e o que comer no lugar",
    descricao: "Os 10 principais alimentos inflamatórios, por que causam inflamação crônica e o que comer no lugar de cada um para recuperar sua saúde.",
    data: "29 de abril de 2026",
    tempo: "9 min de leitura",
    tag: "Saúde & Inflamação",
    emoji: "🔥",
  },
  {
    slug: "quantas-calorias-preciso-por-dia",
    titulo: "Quantas calorias eu preciso por dia?",
    descricao: "Aprenda a calcular sua TMB e TDEE com a fórmula Mifflin-St Jeor e descubra quantas calorias comer para emagrecer, manter ou ganhar peso.",
    data: "28 de abril de 2026",
    tempo: "9 min de leitura",
    tag: "Nutrição",
    emoji: "🔢",
  },
  {
    slug: "proteina-no-cafe-da-manha",
    titulo: "Proteína no café da manhã: por que é tão importante e o que comer",
    descricao: "A ciência por trás do café da manhã proteico e 10 opções práticas com alimentos brasileiros para começar hoje.",
    data: "26 de abril de 2026",
    tempo: "7 min de leitura",
    tag: "Nutrição",
    emoji: "🍳",
  },
  {
    slug: "cardapio-saudavel-para-semana",
    titulo: "Cardápio saudável para a semana: 5 dias de refeições prontas",
    descricao: "Planejamento alimentar completo de segunda a sexta com café da manhã, almoço, lanche e jantar. Inclui lista de compras.",
    data: "25 de abril de 2026",
    tempo: "10 min de leitura",
    tag: "Alimentação Saudável",
    emoji: "🥗",
  },
  {
    slug: "quanto-tempo-para-ver-resultado-no-jejum-intermitente",
    titulo: "Quanto tempo leva para ver resultado no jejum intermitente?",
    descricao: "A linha do tempo real do que acontece no seu corpo — da 1ª semana até 3 meses de jejum intermitente, sem enrolação.",
    data: "24 de abril de 2026",
    tempo: "8 min de leitura",
    tag: "Jejum Intermitente",
    emoji: "⏱️",
  },
  {
    slug: "jejum-intermitente-16-8-para-iniciantes",
    titulo: "Jejum intermitente 16:8 para iniciantes: guia completo para começar hoje",
    descricao: "Entenda como funciona o jejum 16:8, qual o melhor horário para começar, o que comer na janela alimentar e os erros mais comuns de quem está começando.",
    data: "24 de abril de 2025",
    tempo: "9 min de leitura",
    tag: "Jejum Intermitente",
    emoji: "⏳",
  },
  {
    slug: "o-que-comer-no-jejum-intermitente-16-8",
    titulo: "O que comer no jejum intermitente 16:8 — guia completo",
    descricao: "Descubra o que comer, quando comer e o que evitar no jejum intermitente 16:8 para maximizar seus resultados.",
    data: "18 de abril de 2025",
    tempo: "8 min de leitura",
    tag: "Jejum Intermitente",
    emoji: "⏰",
  },
  {
  slug: "como-emagrecer-sem-passar-fome",
  titulo: "Como emagrecer sem passar fome — 7 estratégias que funcionam",
  descricao: "Esqueça as dietas radicais. Veja 7 estratégias comprovadas para emagrecer sem sofrimento.",
  data: "20 de abril de 2026",
  tempo: "10 min de leitura",
  tag: "Emagrecimento",
  emoji: "🔥",
  },
  {
    slug: "low-carb-para-iniciantes",
    titulo: "Low carb para iniciantes: o que é, como começar e cardápio de exemplo",
    descricao: "Guia completo para quem quer começar a dieta low carb do zero. O que comer, o que evitar e um cardápio de exemplo para a primeira semana.",
    data: "17 de abril de 2025",
    tempo: "10 min de leitura",
    tag: "Low Carb",
    emoji: "🥑",
  },
];

export default function Blog() {
  return (
    <>
      <header className={styles.header}>
        <Link href="/" className={styles.logo}>Nutry<span className={styles.logoAccent}>.life</span></Link>
        <div style={{ display: 'flex', gap: '15px', alignItems: 'center' }}>
          <Link href="/login" className={styles.btnEntrar}>Entrar</Link>
          <div className={styles.badge}>Beta</div>
        </div>
      </header>

      <main className={styles.main}>
        <div className="fade-up">

          <div className={styles.heroEyebrow}>
            <div className={styles.heroLine} />
            <span className={styles.heroEyebrowText}>Conteúdo gratuito</span>
          </div>
          <h1 className={styles.heroTitle}>
            Blog <em className={styles.heroEm}>Nutry.life</em>
          </h1>
          <p className={styles.heroSub}>
            Artigos completos sobre nutrição, dietas e alimentação saudável escritos pela nossa equipe para te ajudar a tomar as melhores decisões alimentares.
          </p>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem', marginBottom: '3rem' }}>
            {posts.map((post) => (
              <Link
                key={post.slug}
                href={`/blog/${post.slug}`}
                style={{ textDecoration: 'none' }}
              >
                <div className={styles.mealCard} style={{ padding: 0, cursor: 'pointer', transition: 'all 0.2s' }}>
                  <div style={{ padding: '1.75rem' }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '0.75rem', flexWrap: 'wrap' }}>
                      <span className={styles.tag}>{post.tag}</span>
                      <span style={{ fontSize: '0.82rem', color: '#9ca3af', fontWeight: 600 }}>{post.data}</span>
                      <span style={{ fontSize: '0.82rem', color: '#9ca3af', fontWeight: 600 }}>· {post.tempo}</span>
                    </div>
                    <div style={{ display: 'flex', gap: '1rem', alignItems: 'flex-start' }}>
                      <div style={{ fontSize: '2.5rem', flexShrink: 0 }}>{post.emoji}</div>
                      <div>
                        <h2 style={{ fontSize: '1.2rem', fontWeight: 800, color: '#111827', marginBottom: '0.5rem', letterSpacing: '-0.3px', lineHeight: 1.3 }}>
                          {post.titulo}
                        </h2>
                        <p style={{ fontSize: '0.92rem', color: '#6b7280', lineHeight: 1.6, fontWeight: 500 }}>
                          {post.descricao}
                        </p>
                      </div>
                    </div>
                    <div style={{ marginTop: '1rem', display: 'flex', alignItems: 'center', gap: '6px', color: '#16a34a', fontWeight: 700, fontSize: '0.9rem' }}>
                      Ler artigo completo →
                    </div>
                  </div>
                </div>
              </Link>
            ))}
          </div>

          <div className={styles.tipCard}>
            <div className={styles.tipIcon}>📬</div>
            <div>
              <div className={styles.tipTitle}>Novos artigos toda semana</div>
              <div className={styles.tipText}>
                Nossa equipe publica conteúdo novo toda semana sobre nutrição, dietas e alimentação saudável. Volte sempre!
              </div>
            </div>
          </div>

          <div className={styles.premiumBanner} style={{ marginTop: '2rem' }}>
            <div className={styles.premiumBadgeTop}>✦ GRÁTIS PARA COMEÇAR</div>
            <div className={styles.premiumHeader}>
              <h2>Pronto para colocar em prática?</h2>
              <p>Gere seu plano alimentar personalizado com IA agora mesmo.</p>
            </div>
            <Link href="/" className={styles.premiumBtn} style={{ textDecoration: 'none', display: 'block' }}>
              Gerar meu plano grátis →
            </Link>
            <p className={styles.premiumFootnote}>Sem cadastro. Sem cartão. 100% grátis.</p>
          </div>

        </div>
      </main>
    </>
  );
}
